package com.epam.entity;

//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.*;

@Getter
@Setter
@ToString
@NoArgsConstructor
@AllArgsConstructor
@Data
@Entity
//@DynamoDBTable(tableName = "books")
public class Book {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
//	@DynamoDBHashKey
//	@DynamoDBAutoGeneratedKey
	private String bookId;
//	@DynamoDBAttribute
	private String name;
//	@DynamoDBAttribute
	private String publisher;
//	@DynamoDBAttribute
	private String author;
	
	public Book(String name, String publisher, String author) {
		super();
		this.name = name;
		this.publisher = publisher;
		this.author = author;
	}

}
